### ISSUE TITLE
'dict object' has no attribute 'description'

### ISSUE THREAD

**Issue by Yamilquery** [GuillaumeSmaha/ansible-role-gluu-configuration#4]
Hi,

I want to create Gluu Custom Scripts by following the examples in the documentation.
However, I'm getting an error:

```
TASK [GuillaumeSmaha.gluu-configuration : Update Scripts - Scripts With Inum] ********************************************************
fatal: [root@157.245.142.85]: FAILED! => {"msg": "'dict object' has no attribute 'description'"}
        to retry, use: --limit @/Users/yamildiazaguirre/.ansible/roles/GuillaumeSmaha.gluu-setup/example/deploy.retry
```

I think that this issue could be related to the `description` in this file:
https://github.com/GuillaumeSmaha/ansible-role-gluu-configuration/blob/6755a858159e0b240295f0087762e5b389b7d937/filter_plugins/gluu_concat_inum.py

**Comment by GuillaumeSmaha** [comment]
Did you add a description in your gluu script ?
I think this is related to this line: https://github.com/GuillaumeSmaha/ansible-role-gluu-configuration/blob/master/tasks/configurations/scripts.yml#L20 or https://github.com/GuillaumeSmaha/ansible-role-gluu-configuration/blob/master/tasks/configurations/scripts.yml#L32

**Comment by Yamilquery** [comment]
Thanks for your answer.

I've just included `GuillaumeSmaha.gluu-configuration` in my `deploy.yml`.

So I guess the `configurations/scripts.yml` should be running without any additional step.

Unfortunately, I always get the same result.

**Edit:**
I've modified my `configurations/scripts.yml` by removing the description attribute and it works. But would be great if you modify it. I'm going to make a pull request.

However, you need to rename `uma_authorization_policy` to `uma_rpt_policy` in your documentation, according to this issue https://github.com/GluuFederation/oxTrust/issues/590.

By other side, I'm getting this error when I try to use your example:

I'm getting the following error In my `/opt/gluu/jetty/oxauth/logs/oxauth_script.log`:

```
[org.xdi.service.custom.script.CustomScriptManager] (CustomScriptManager.java:120) - Exception happened while reloading custom scripts configuration
org.gluu.site.ldap.persistence.exception.MappingException: Failed to convert json value '{'value2': '@!B6EB.8785.1904.6D8F!0001!9997.7C97!0008!2212.0010', 'value1': 'allowed_clients', 'description': ''}' to object
	at org.gluu.site.ldap.persistence.AbstractEntryManager.convertStringToJson(AbstractEntryManager.java:1115) ~[oxcore-ldap-3.1.4.Final.jar:?]
```

**Comment by GuillaumeSmaha** [comment]
What is your Gluu version ? My last update was for Gluu 3.1.4 and the script was initially made for Gluu 3.0.x

**Comment by Yamilquery** [comment]
I have the same 3.1.4. 

It seems that can't convert the `"value2":"{{ gluu_inum_org }}!0008!2212.0010"` to a valid JSON.

I notice a weird behavior.
If I change `"value2":"{{ gluu_inum_org }}!0008!2212.0010"` by a string like `"value2":"@!E9F6.CC47.6E77.3BAC!0001!78F2.981E!0008!2212.0010"` it works, but when I use the print statement `{{ whatever }}` Gluu show the previous error.

**Comment by GuillaumeSmaha** [comment]
I am using ansible 2.9.4.

I added log during installation: 
```
TASK [GuillaumeSmaha.gluu-configuration : Update Scripts - Scripts Without Inum - Debug] **************************************************************************************************************************************************************************************
ok: [gluu-ubuntu] => (item=basic_lock - Basic Authentication with Lock) => {
    "msg": {
        "description": "Basic Authentication with Lock", 
        "displayName": "basic_lock", 
        "gluuStatus": "false", 
        "objectClass": [
            "top", 
            "oxCustomScript"
        ], 
        "oxConfigurationProperty": [
            "{\"value1\":\"invalid_login_count_attribute\",\"value2\":\"oxCountInvalidLogin\",\"description\":\"\"}", 
            "{\"value1\":\"maximum_invalid_login_attemps\",\"value2\":\"10\",\"description\":\"\"}"
        ], 
        "oxRevision": 1
    }
}
ok: [gluu-ubuntu] => (item=uma_rpt_policy - UMA Authorization Policy) => {
    "msg": {
        "description": "UMA Authorization Policy", 
        "displayName": "uma_rpt_policy", 
        "gluuStatus": "false", 
        "objectClass": [
            "top", 
            "oxCustomScript"
        ], 
        "oxConfigurationProperty": [
            {
                "description": "", 
                "value1": "allowed_clients", 
                "value2": "@!3E7E.3BD4.70F1.B21C!0001!0F6D.BDCE!0008!2212.0010"
            }
        ], 
        "oxRevision": 1
    }
}
```

The second part for `oxConfigurationProperty` is not escaped and I got an error to load admin page for custom scripts
[identify.jetty.log](https://github.com/GuillaumeSmaha/ansible-role-gluu-configuration/files/4242641/identify.jetty.log)


If I replaced like you said `@!3E7E.3BD4.70F1.B21C!0001!0F6D.BDCE` by `@!3E7E.3BD4.70F1.B21C!0001!0F6D.BDCE`, I got the good payload and no error on the custom scripts:

```
        "oxConfigurationProperty": [
            "{\"value1\":\"allowed_clients\",\"value2\":\"@!3E7E.3BD4.70F1.B21C!0001!0F6D.BDCE!0008!2212.0010\",\"description\":\"\"}"
        ],
```

**Comment by GuillaumeSmaha** [comment]
I just find an issue related to this behavior: https://github.com/ansible/ansible/issues/46169

**Comment by GuillaumeSmaha** [comment]
As workaround you can use this:
`'{{ ''{"value1":"allowed_clients","value2":"{{ gluu_inum_org }}!0008!2212.0010","description":""}'' | to_json }}'`

**Comment by Yamilquery** [comment]
Thank you for your answer. Unfortunately, it doesn't work for me.

I try your previous solution, but I'm getting this:

**oxauth_script.log**

`org.gluu.site.ldap.persistence.exception.MappingException: Failed to convert json value '"{\"value1\":\"allowed_clients\",\"value2\":\"@!1CA1.C152.5481.EDF6!0001!B423.B8BA!0008!2212.0010\",\"description\":\"\"}"' to object`

**Comment by GuillaumeSmaha** [comment]
Are you using python2 or 3 with ansible ? I am using python2:
```ansible-playbook --version
ansible-playbook 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gsm/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]```

**Comment by GuillaumeSmaha** [comment]
I tried with python3, and I got the same result. Can you add this patch in the role to display the content pushed in Gluu LDAP:
```patch
diff --git a/tasks/configurations/scripts.yml b/tasks/configurations/scripts.yml
index d2d62e0..f8dcc78 100644
--- a/tasks/configurations/scripts.yml
+++ b/tasks/configurations/scripts.yml
@@ -19,6 +19,15 @@
   loop_control:
     label: "{{ item.displayName }} - {{ item.description }}"
 
+- name: "Update Scripts - Scripts With Inum - Debug"
+  debug:
+    msg: "{{ gluu_scripts_default | combine(item, recursive=True) | gluu_concat_inum(base_inum=gluu_inum_org, inum_type='0011') }}"
+  with_items:
+    "{{ gluu_scripts | default([]) }}"
+  when: item.inum is defined
+  loop_control:
+    label: "{{ item.displayName }} - {{ item.description }}"
+
 - name: "Update Scripts - Scripts Without Inum"
   ldap_upsert:
     params: "{{ ldap_params }}"
@@ -30,3 +39,12 @@
   when: item.inum is not defined
   loop_control:
     label: "{{ item.displayName }} - {{ item.description }}"
+
+- name: "Update Scripts - Scripts Without Inum - Debug"
+  debug:
+    msg: "{{ gluu_scripts_default | combine(item, recursive=True) }}"
+  with_items:
+    "{{ gluu_scripts | default([]) }}"
+  when: item.inum is not defined
+  loop_control:
+    label: "{{ item.displayName }} - {{ item.description }}"

```

**Comment by Yamilquery** [comment]
Before I was using Ansible 2.9.4, but in order to work, I downgrade to 2.5.15, after receiving an error:

`Skipping plugin (/Users/yamildiazaguirre/.ansible/roles/GuillaumeSmaha.gluu-configuration/filter_plugins/gluu_encrypt_password.py) as it seems to be invalid: No module named 'pyDes'`.

Anyway, I upgrade ansible and python again:
```
ansible-playbook 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/yamildiazaguirre/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.4_1/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.1 (default, Feb 10 2020, 10:34:03) [Clang 11.0.0 (clang-1100.0.33.17)]
```

But when I use this Ansible version, I get:

```
TASK [GuillaumeSmaha.gluu-configuration : Update OpenID Connect - Clients - User With Inum] ***************************************************************************************************************************************************************
fatal: [root@167.172.151.179]: FAILED! => {"msg": "template error while templating string: no filter named 'gluu_encrypt_password'. String: {{ gluu_openid_connect_clients_default | combine(item, recursive=True) | gluu_encrypt_password(key='oxAuthClientSecret', secret=gluu_ldap_salt_password) | gluu_concat_inum(base_inum=gluu_inum_org, inum_type='0008') | gluu_concat_inum(key='oxAuthScope', base_inum=gluu_inum_org, inum_type='0009', dn='scopes') }}"}
```

**Comment by GuillaumeSmaha** [comment]
For `pyDes`, just call `pip3 install pyDes` (`pip3 install --user pyDes` or `sudo pip3 install pyDes`)

**Comment by Yamilquery** [comment]
Haha, my mistake, thank you. (I had to install it with `/usr/local/Cellar/ansible/2.9.4_1/libexec/bin/pip install pyDes` because Ansible uses their own `python` and `pip` version.)

I included your patch to debug, and these were my results.
```
TASK [GuillaumeSmaha.gluu-configuration : Update Scripts - Scripts Without Inum - Debug] ***
ok: [root@64.227.0.134] => (item=basic_lock) => {
    "msg": {
        "description": null,
        "displayName": "basic_lock",
        "gluuStatus": "true",
        "objectClass": [
            "top",
            "oxCustomScript"
        ],
        "oxConfigurationProperty": [
            "{\"value1\":\"invalid_login_count_attribute\",\"value2\":\"oxCountInvalidLogin\",\"description\":\"\"}",
            "{\"value1\":\"maximum_invalid_login_attemps\",\"value2\":\"10\",\"description\":\"\"}"
        ],
        "oxRevision": 1
    }
}
ok: [root@64.227.0.134] => (item=uma_rpt_policy) => {
    "msg": {
        "description": null,
        "displayName": "uma_rpt_policy",
        "gluuStatus": "true",
        "objectClass": [
            "top",
            "oxCustomScript"
        ],
        "oxConfigurationProperty": [
            "\"{\\\"value1\\\":\\\"allowed_clients\\\",\\\"value2\\\":\\\"{{ gluu_inum_org }}!0008!2212.0010\\\",\\\"description\\\":\\\"\\\"}\""
        ],
        "oxRevision": 1
    }
}
```

Again, all the steps were executed successfully, but my `oxauth_script.log` shows the same error:

```
org.gluu.site.ldap.persistence.exception.MappingException: Failed to convert json value '"{\"value1\":\"allowed_clients\",\"value2\":\"{{ gluu_inum_org }}!0008!2212.0010\",\"description\":\"\"}"' to object
```

Also, I tried by the old way, but it's the same:
```
org.gluu.site.ldap.persistence.exception.MappingException: Failed to convert json value '{'value2': '@!5B94.6438.500F.7812!0001!3331.E1EB!0008!2212.0010', 'value1': 'allowed_clients', 'description': ''}' to object
```

**Comment by GuillaumeSmaha** [comment]
Sure. This line `"\"{\\\"value1\\\":\\\"allowed_clients\\\",\\\"value2\\\":\\\"{{ gluu_inum_org }}!0008!2212.0010\\\",\\\"description\\\":\\\"\\\"}\""` has too many escaping and `{{ gluu_inum_org }}` is not correctly replaced by the value. 

On the last, the single quote should be double quote ...

**Comment by GuillaumeSmaha** [comment]
What is the result of the debug message with the old way ?

**Comment by GuillaumeSmaha** [comment]
Maybe I should take a real dict object as input and call `to_json` on it.
I am creating a branch to test it

**Comment by Yamilquery** [comment]
> What is the result of the debug message with the old way ?

I used this in my `main.yml`

```
-
    displayName: uma_rpt_policy
    gluuStatus: 'true'
    oxConfigurationProperty:
      - '{"value1": "allowed_clients", "value2": "{{ gluu_inum_org }}!0008!2212.0010", "description": ""}'
```

And, this is the result:

```
TASK [GuillaumeSmaha.gluu-configuration : Update Scripts - Scripts Without Inum - Debug] ******************************
ok: [root@159.89.85.107] => (item=basic_lock) => {
    "msg": {
        "description": null,
        "displayName": "basic_lock",
        "gluuStatus": "true",
        "objectClass": [
            "top",
            "oxCustomScript"
        ],
        "oxConfigurationProperty": [
            "{\"value1\":\"invalid_login_count_attribute\",\"value2\":\"oxCountInvalidLogin\",\"description\":\"\"}",
            "{\"value1\":\"maximum_invalid_login_attemps\",\"value2\":\"10\",\"description\":\"\"}"
        ],
        "oxRevision": 1
    }
}
ok: [root@159.89.85.107] => (item=uma_rpt_policy) => {
    "msg": {
        "description": null,
        "displayName": "uma_rpt_policy",
        "gluuStatus": "true",
        "objectClass": [
            "top",
            "oxCustomScript"
        ],
        "oxConfigurationProperty": [
            {
                "description": "",
                "value1": "allowed_clients",
                "value2": "@!5B94.6438.500F.7812!0001!3331.E1EB!0008!2212.0010"
            }
        ],
        "oxRevision": 1
    }
}
```

**Comment by Yamilquery** [comment]
> Maybe I should take a real dict object as input and call `to_json` on it.
> I am creating a branch to test it

It would be great, I hope it works!

**Comment by GuillaumeSmaha** [comment]
I found a way by adding a new filter to do the conversion. And I found in another filter this comment `# Add whitespace to avoid implicit conversion to dict by python`
It seems python + ansible +jinja2 is a mess :D

**Comment by GuillaumeSmaha** [comment]
@Yamilquery can you try this branch ? https://github.com/GuillaumeSmaha/ansible-role-gluu-configuration/tree/use_real_dict_for_oxConfigurationProperty (commit https://github.com/GuillaumeSmaha/ansible-role-gluu-configuration/commit/1321ef4530b6e62e3219b9d9735736fbd88c0475)

I kept the debug message to check if it doesn't work.

**Comment by Yamilquery** [comment]
Thank you for your commit, but it doesn't work for me.

I'm getting this:
```
TASK [GuillaumeSmaha.gluu-configuration : Update Scripts - Scripts With Inum] *****************************************
failed: [root@104.248.127.154] (item={'displayName': 'basic_lock', 'gluuStatus': 'true', 'oxConfigurationProperty': ['{"value1":"invalid_login_count_attribute","value2":"oxCountInvalidLogin","description":""}', '{"value1":"maximum_invalid_login_attemps","value2":"10","description":""}']}) => {"ansible_loop_var": "item", "changed": false, "item": {"displayName": "basic_lock", "gluuStatus": "true", "oxConfigurationProperty": ["{\"value1\":\"invalid_login_count_attribute\",\"value2\":\"oxCountInvalidLogin\",\"description\":\"\"}", "{\"value1\":\"maximum_invalid_login_attemps\",\"value2\":\"10\",\"description\":\"\"}"]}, "msg": "Failed to template loop_control.label: 'dict object' has no attribute 'description'", "skip_reason": "Conditional result was False"}
failed: [root@104.248.127.154] (item={'displayName': 'uma_rpt_policy', 'gluuStatus': 'true', 'oxConfigurationProperty': [{'value1': 'allowed_clients', 'value2': '@!E1E0.899E.ACC8.7C05!0001!6801.37C7!0008!2212.0010', 'description': ''}]}) => {"ansible_loop_var": "item", "changed": false, "item": {"displayName": "uma_rpt_policy", "gluuStatus": "true", "oxConfigurationProperty": [{"description": "", "value1": "allowed_clients", "value2": "@!E1E0.899E.ACC8.7C05!0001!6801.37C7!0008!2212.0010"}]}, "msg": "Failed to template loop_control.label: 'dict object' has no attribute 'description'", "skip_reason": "Conditional result was False"}
```

**Comment by Yamilquery** [comment]
Thank you for your commit, sadly it did not work.

```
org.gluu.site.ldap.persistence.exception.MappingException: Failed to convert json value ' "{\"value1\":\"invalid_login_count_attribute\",\"value2\":\"oxCountInvalidLogin\",\"description\":\"\"}"' to object
```

Did you make it work?

**Comment by GuillaumeSmaha** [comment]
Weird, you have double quote around your JSON payload.
Can you share the debug message ?

On my side, yes it works and I can see the extra space at the beginning: ` {"value1": "invalid_login_count_attribute", "value2": "oxCountInvalidLogin", "description": ""}`

**Comment by Yamilquery** [comment]
My mistake, it works perfectly fine!

Feel free to close the issue.

Thank you so much!

**Comment by GuillaumeSmaha** [comment]
Nice, I also tries with Gluu 3.1.7 and it works too :)
For Gluu 4.0.0, I think it will need some update

**Comment by GuillaumeSmaha** [comment]
Nice, I also tries with Gluu 3.1.7 and it works too :)
For Gluu 4.0.0, I think it will need some update
